version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: painting_db
    environment:
      POSTGRES_DB: painting_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d painting_service"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: painting_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Node.js API Server
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: painting_api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql://admin:password123@postgres:5432/painting_service"
      REDIS_URL: "redis://redis:6379"
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: "your-super-secret-jwt-key-change-in-production"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
